:Author: ard12sgf1960
:Email:
:Date: 25/05/2023
:Revision: version#
:License: Public Domain

= Project: {Project}

Read temperature and humidity and upload to the Arduino IOT

== Step 1: Installation

1. Set up your device on Ardiuno
2. Add the variables to a Thing associated with your device

String xiao_19_comfort;
float xiao_19_depoint;
float xiao_19_heatindex;
float xiao_19_humidity;
float xiao_19_temperature;

3. Change the code in thingProperties.h to include your unique ID const char DEVICE_LOGIN_NAME[]  = "a9ea85e0-a199-4816-aca4-a77a6ac14ddf" 
4. Add your internet details on the Secrets.h
5. load to your device
6. Create a dashboard to show the outputs

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Xiao_Weather_may25a                => Arduino sketch folder
  ├── Xiao_Weather_may25a.ino       => main Arduino file
  ├── thingProperties.h             => Arduino library file
  ├── arduino_secrets.h             => data about internet and device
  └── Xiao ESP32 DHT11.pdf          => schematic 
....

=== License
This project is released under a {Public Open} License.

=== Contributing
To contribute to this project please contact: steve.f.fuller@gmail.com

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 1    
| L1 | DHT11          | 2345-asdf   | 1      
| A1 | Xiao ESP32C3   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
